### ISSUE TITLE
Article Edit Button Disappears on Mobile in the Denim Themes

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1077]
Issue first mentioned in the Geeklog Forum: https://www.geeklog.net/forum/viewtopic.php?showtopic=97315

Should check both the Denim and Denim 3 themes for issue.

To save space the edit icon disappears from the page on mobile devices but that means it is not easy for an admin on a mobile device to edit an article. It should remain.

We should also add Edit Article for those with access to the Article Options (like we do for other admin options like Send Ping)

**Comment by mystralkk** [comment]
Fixed with change set 8e5c8528a23dc3611f2cae6086f26dc4d6679cf7.  The cause of this issue was:
```CSS
@media only screen and (max-width: 959px) {

  .story_icon {
    display: none;
  }
}
```
